version = 3.9.8
runner.dialect = scala3
docstrings.wrap = no
importSelectors = singleLine
maxColumn = 120
project.git = true
rewrite.rules = [Imports, RedundantParens, SortModifiers, PreferCurlyFors]
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [
  ["scala\\..*"],
  ["javax?\\..*"]
]
rewrite.sortModifiers.order = ["override", "private", "protected", "implicit", "final", "sealed", "abstract", "lazy"]
rewrite.trailingCommas.style = multiple
rewrite.trailingCommas.allowFolding = true

rewrite.scala3.removeOptionalBraces = true
rewrite.scala3.convertToNewSyntax = true
